### ISSUE TITLE
Inconsitent splitting of strings

### ISSUE THREAD

**Issue by JasperWB** [dotTHzTAG/pydotthz#2]
The splitting of strings during loading relies on there being spaces after the comma (i.e. "Sample, Reference" works while "Sample,Reference", the current output from CaTx, doesn't). This is fixed in my current pull request re the load constructor, but if you don't want to accept that pull a whitespace neutral way of splitting is: split_string = [x.strip() for x in string.split(',')]

**Comment by hacknus** [comment]
solved with #1
